name: Daily CI

on:
  schedule:
    # Daily run this action at 1am
    - cron: '0 1 * * *'

jobs:
  build-on-ubuntu-without-jemalloc:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Build
        run: |
          git submodule init && git submodule update
          mkdir _build && cd _build
          cmake -DDISABLE_JEMALLOC=true -DCMAKE_BUILD_TYPE=Release ..
          make -j4 kvrocks kvrocks2redis
          cp kvrocks ../src && cd ..

      - name: Redis Tcl Test
        run: |
          sudo apt-get install tcl8.5
          cd tests/tcl && sh runtest && cd -

  build-test-on-macos-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          brew install snappy googletest gcc autoconf automake libtool
          mkdir build
      - name: Build
        run: |
          make -j4
          cp src/kvrocks build/kvrocks
      - name: Unit Test
        run: make test

      - name: Redis Tcl Test
        run:
          cd tests/tcl && sh runtest && cd -