name: kvrocks ci actions  # don't edit while the badge was depend on this

on: [push, pull_request]

jobs:
  lint-build-test-on-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          sudo pip install --upgrade pip
          sudo pip install --upgrade setuptools
          sudo apt-get update
          sudo apt-get install -y cppcheck
          sudo pip install cpplint==1.5.0
          sudo apt-get install -y tar libsnappy-dev
          mkdir build

      - name: Lint
        run: |
          make lint

      - name: Build
        run: |
          make -j4
          cp src/kvrocks build/kvrocks

      - name: Unit Test
        run: |
          wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
          tar -zxvf release-1.8.1.tar.gz
          cd googletest-release-1.8.1/
          cmake CMakeLists.txt
          make && sudo make install && cd -
          make test

      - name: Redis Tcl Test
        run: |
          wget https://github.com/redis/redis/archive/refs/tags/6.2.6.tar.gz
          tar -zxvf 6.2.6.tar.gz
          cd redis-6.2.6/ && make redis-cli && cd -
          cp redis-6.2.6/src/redis-cli tests/tcl/redis-cli
          sudo apt-get install tcl8.5
          cd tests/tcl && sh runtest
          sh runtest --single integration/redis-cli && cd -

  build-on-macos-latest:
    runs-on: macos-11
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          brew install snappy googletest gcc autoconf automake libtool
          mkdir build

      - name: Build
        run: make -j4